# Generated by Django 2.0.6 on 2018-07-08 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_userprofile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, verbose_name='群名')),
                ('brief', models.CharField(default='', max_length=255, verbose_name='群简介')),
                ('max_members_limit', models.PositiveIntegerField(default=200, verbose_name='最大成员数')),
                ('admins', models.ManyToManyField(blank=True, related_name='managed_groups', to='account.UserProfile', verbose_name='管理员')),
                ('members', models.ManyToManyField(blank=True, related_name='belonged_groups', to='account.UserProfile', verbose_name='群成员')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='account.UserProfile', verbose_name='群主')),
            ],
            options={
                'verbose_name': '群组',
                'verbose_name_plural': '群组',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('single', '个人'), ('group', '群')], default='single', max_length=10, verbose_name='信息类型(个人/群)')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_received', to='account.UserProfile', verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sent', to='account.UserProfile', verbose_name='发送者')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
